-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2021-04-05 18:36:31 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE birth_year (
    birth INTEGER NOT NULL
);

ALTER TABLE birth_year ADD CONSTRAINT birth_year_pk PRIMARY KEY ( birth );

CREATE TABLE class_info (
    classprofilename  VARCHAR(255) NOT NULL,
    classlangname     VARCHAR(255) NOT NULL
);

ALTER TABLE class_info ADD CONSTRAINT class_info_pk PRIMARY KEY ( classprofilename,
                                                                  classlangname );

CREATE TABLE education_institution (
    eoname      VARCHAR(255) NOT NULL,
    eoparent    VARCHAR(255) NOT NULL,
    eotypename  VARCHAR(255) NOT NULL,
    eoregname   VARCHAR(255) NOT NULL,
    eoareaname  VARCHAR(255) NOT NULL,
    eotername   VARCHAR(255) NOT NULL
);

ALTER TABLE education_institution
    ADD CONSTRAINT education_institution_pk PRIMARY KEY ( eoname,
                                                          eoparent,
                                                          eotypename,
                                                          eotername );

CREATE TABLE inst_type (
    eotypename VARCHAR(255) NOT NULL
);

ALTER TABLE inst_type ADD CONSTRAINT inst_type_pk PRIMARY KEY ( eotypename );

CREATE TABLE institution_location (
    eoragname   VARCHAR(255) NOT NULL,
    eoareaname  VARCHAR(255) NOT NULL,
    eotername   VARCHAR(255) NOT NULL
);

ALTER TABLE institution_location
    ADD CONSTRAINT institution_location_pk PRIMARY KEY ( eoragname,
                                                         eoareaname,
                                                         eotername );

CREATE TABLE sex (
    sextypename VARCHAR(255) NOT NULL
);

ALTER TABLE sex ADD CONSTRAINT sex_pk PRIMARY KEY ( sextypename );

CREATE TABLE student (
    outid             VARCHAR(40) NOT NULL,
    eoname            VARCHAR(255) NOT NULL,
    classprofilename  VARCHAR(255) NOT NULL,
    classlangname     VARCHAR(255) NOT NULL,
    birth             INTEGER NOT NULL,
    regtypename       VARCHAR(255) NOT NULL,
    sextypename       VARCHAR(255) NOT NULL,
    regname           VARCHAR(255) NOT NULL,
    areaname          VARCHAR(255) NOT NULL,
    tername           VARCHAR(255) NOT NULL,
    eoparent          VARCHAR(255) NOT NULL,
    eotypename        VARCHAR(255) NOT NULL,
    eotername         VARCHAR(255) NOT NULL
);

ALTER TABLE student ADD CONSTRAINT student_pk PRIMARY KEY ( outid );

CREATE TABLE student_location (
    regname      VARCHAR(255) NOT NULL,
    areaname     VARCHAR(255) NOT NULL,
    tername      VARCHAR(255) NOT NULL,
    tertypename  VARCHAR(255) NOT NULL
);

ALTER TABLE student_location
    ADD CONSTRAINT student_location_pk PRIMARY KEY ( regname,
                                                     areaname,
                                                     tername );

CREATE TABLE student_type (
    regtypename VARCHAR(255) NOT NULL
);

ALTER TABLE student_type ADD CONSTRAINT student_type_pk PRIMARY KEY ( regtypename );

CREATE TABLE ter_type (
    tertypename VARCHAR(255) NOT NULL
);

ALTER TABLE ter_type ADD CONSTRAINT ter_type_pk PRIMARY KEY ( tertypename );

CREATE TABLE test_info (
    outid           VARCHAR(40) NOT NULL,
    year            INTEGER NOT NULL,
    ukrtest         VARCHAR(255),
    ukrteststatus   VARCHAR(255),
    ukrball100      INTEGER,
    ukrball12       INTEGER,
    ukrball         INTEGER,
    ukradaptskale   VARCHAR(255),
    ukrptname       VARCHAR(255),
    ukrptregname    VARCHAR(255),
    ukrptareaname   VARCHAR(255),
    ukrpttername    VARCHAR(255),
    histtest        VARCHAR(255),
    histlang        VARCHAR(255),
    histteststatus  VARCHAR(255),
    histball100     INTEGER,
    histball12      INTEGER,
    histball        INTEGER,
    histptname      VARCHAR(255),
    histptregname   VARCHAR(255),
    histptareaname  VARCHAR(255),
    histpttername   VARCHAR(255),
    mathtest        VARCHAR(255),
    mathlang        VARCHAR(255),
    mathteststatus  VARCHAR(255),
    mathball100     INTEGER,
    mathball12      INTEGER,
    mathball        INTEGER,
    mathptname      VARCHAR(255),
    mathptregname   VARCHAR(255),
    mathptareaname  VARCHAR(255),
    mathpttername   VARCHAR(255),
    phystest        VARCHAR(255),
    physlang        VARCHAR(255),
    physteststatus  VARCHAR(255),
    physball100     INTEGER,
    physball12      INTEGER,
    physball        INTEGER,
    physptname      VARCHAR(255),
    physptregname   VARCHAR(255),
    physptareaname  VARCHAR(255),
    physpttername   VARCHAR(255),
    chemtest        VARCHAR(255),
    chemlang        VARCHAR(255),
    chemteststatus  VARCHAR(255),
    chemball100     INTEGER,
    chemball12      INTEGER,
    chemball        INTEGER,
    chemptname      VARCHAR(255),
    chemptregname   VARCHAR(255),
    chemptareaname  VARCHAR(255),
    chempttername   VARCHAR(255),
    biotest         VARCHAR(255),
    biolang         VARCHAR(255),
    bioteststatus   VARCHAR(255),
    bioball100      INTEGER,
    bioball12       INTEGER,
    bioball         INTEGER,
    bioptname       VARCHAR(255),
    bioptregname    VARCHAR(255),
    bioptareaname   VARCHAR(255),
    biopttername    VARCHAR(255),
    geotest         VARCHAR(255),
    geolang         VARCHAR(255),
    geoteststatus   VARCHAR(255),
    geoball100      INTEGER,
    geoball12       INTEGER,
    geoball         INTEGER,
    geoptname       VARCHAR(255),
    geoptregname    VARCHAR(255),
    geoptareaname   VARCHAR(255),
    geopttername    VARCHAR(255),
    engtest         VARCHAR(255),
    engteststatus   VARCHAR(255),
    engball100      INTEGER,
    engball12       INTEGER,
    engdpalevel     VARCHAR(255),
    engball         INTEGER,
    engptname       VARCHAR(255),
    engptregname    VARCHAR(255),
    engptareaname   VARCHAR(255),
    engpttername    VARCHAR(255),
    fratest         VARCHAR(255),
    frateststatus   VARCHAR(255),
    fraball100      INTEGER,
    fraball12       INTEGER,
    fradpalevel     VARCHAR(255),
    fraball         INTEGER,
    fraptname       VARCHAR(255),
    fraptregname    VARCHAR(255),
    fraptareaname   VARCHAR(255),
    frapttername    VARCHAR(255),
    deutest         VARCHAR(255),
    deuteststatus   VARCHAR(255),
    deuball100      INTEGER,
    deuball12       INTEGER,
    deudpalevel     VARCHAR(255),
    deuball         INTEGER,
    deuptname       VARCHAR(255),
    deuptregname    VARCHAR(255),
    deuptareaname   VARCHAR(255),
    deupttername    VARCHAR(255),
    spatest         VARCHAR(255),
    spateststatus   VARCHAR(255),
    spaball100      INTEGER,
    spaball12       INTEGER,
    spadpalevel     VARCHAR(255),
    spaball         INTEGER,
    spaptname       VARCHAR(255),
    spaptregname    VARCHAR(255),
    spaptareaname   VARCHAR(255),
    spapttername    VARCHAR(255)
);

ALTER TABLE test_info ADD CONSTRAINT test_info_pk PRIMARY KEY ( outid );

CREATE TABLE test_year (
    year INTEGER NOT NULL
);

ALTER TABLE test_year ADD CONSTRAINT test_year_pk PRIMARY KEY ( year );

ALTER TABLE education_institution
    ADD CONSTRAINT education_inst_type_fk FOREIGN KEY ( eotypename )
        REFERENCES inst_type ( eotypename );

ALTER TABLE education_institution
    ADD CONSTRAINT institution_location_fk FOREIGN KEY ( eoregname,
                                                         eoareaname,
                                                         eotername )
        REFERENCES institution_location ( eoragname,
                                          eoareaname,
                                          eotername );

ALTER TABLE student_location
    ADD CONSTRAINT location_ter_type_fk FOREIGN KEY ( tertypename )
        REFERENCES ter_type ( tertypename );

ALTER TABLE student
    ADD CONSTRAINT student_birth_year_fk FOREIGN KEY ( birth )
        REFERENCES birth_year ( birth );

ALTER TABLE student
    ADD CONSTRAINT student_class_info_fk FOREIGN KEY ( classprofilename,
                                                       classlangname )
        REFERENCES class_info ( classprofilename,
                                classlangname );

ALTER TABLE student
    ADD CONSTRAINT student_inst_fk FOREIGN KEY ( eoname,
                                                 eoparent,
                                                 eotypename,
                                                 eotername )
        REFERENCES education_institution ( eoname,
                                           eoparent,
                                           eotypename,
                                           eotername );

ALTER TABLE student
    ADD CONSTRAINT student_location_fk FOREIGN KEY ( regname,
                                                     areaname,
                                                     tername )
        REFERENCES student_location ( regname,
                                      areaname,
                                      tername );

ALTER TABLE student
    ADD CONSTRAINT student_sex_fk FOREIGN KEY ( sextypename )
        REFERENCES sex ( sextypename );

ALTER TABLE student
    ADD CONSTRAINT student_student_type_fk FOREIGN KEY ( regtypename )
        REFERENCES student_type ( regtypename );

ALTER TABLE test_info
    ADD CONSTRAINT test_info_student_fk FOREIGN KEY ( outid )
        REFERENCES student ( outid );

ALTER TABLE test_info
    ADD CONSTRAINT test_info_test_year_fk FOREIGN KEY ( year )
        REFERENCES test_year ( year );



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0